# Generated by Django 3.2.9 on 2021-12-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='show_on_websity',
            field=models.BooleanField(default=False, verbose_name='Опубликовано?'),
        ),
        migrations.AlterField(
            model_name='page',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='pages', to='pages.Category', verbose_name='Превью для главной'),
        ),
        migrations.AlterField(
            model_name='page',
            name='show_on_main',
            field=models.BooleanField(default=False, verbose_name='Страница в меню'),
        ),
    ]
