# Generated by Django 3.2.9 on 2021-12-19 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20211220_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='adress',
            field=models.TextField(default='', verbose_name='Адресс страницы транскриптом'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='pages', to='pages.Category', verbose_name='Превью для главной'),
        ),
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ImageField(blank=True, help_text='Будет отображаться в статье и в ее миниатюре в списке статей.', upload_to='sys/article_images/', verbose_name='Изображение статьи'),
        ),
        migrations.AlterField(
            model_name='page',
            name='image_description',
            field=models.TextField(blank=True, max_length=400, verbose_name='Описание изображение статьи'),
        ),
    ]
