# Generated by Django 3.2.9 on 2021-12-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapy',
            name='price',
            field=models.CharField(max_length=10, verbose_name='Цена'),
        ),
    ]
