# Generated by Django 3.2.9 on 2021-12-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.ImageField(blank=True, default='sys/service_icons/default.png', upload_to='sys/service_icons/', verbose_name='Иконка услуги'),
        ),
        migrations.AddField(
            model_name='service',
            name='show_on_main',
            field=models.BooleanField(default=False, verbose_name='Показать на главной'),
        ),
    ]
