# Generated by Django 3.2.9 on 2021-12-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20211211_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description_price_block',
            field=models.TextField(default='default', verbose_name='Описани для блока цен'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='title_price_block',
            field=models.TextField(default='default', verbose_name='Заголовок для блока цен'),
            preserve_default=False,
        ),
    ]
