# Generated by Django 3.2.9 on 2021-12-26 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20211226_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicearticle',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_articles', related_query_name='service_article', to='services.service', verbose_name='Услуга'),
        ),
    ]
