# Generated by Django 3.2.9 on 2022-01-19 02:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_therapy_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='information_markdown',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Дополнительная информация об услуге'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='text',
            field=models.TextField(default='', verbose_name='Текст услуги'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(verbose_name='Описание услуги для SEO'),
        ),
        migrations.DeleteModel(
            name='InformationService',
        ),
    ]
