# Generated by Django 3.2.9 on 2021-12-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20211216_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description_price_block',
            field=models.TextField(verbose_name='Описание для блока цен'),
        ),
    ]
