# Generated by Django 3.2.9 on 2022-01-19 03:10

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20220119_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='information_html',
            field=models.TextField(default='', editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=mdeditor.fields.MDTextField(verbose_name='Описание услуги для SEO'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_price_block',
            field=mdeditor.fields.MDTextField(verbose_name='Описание для блока цен'),
        ),
        migrations.AlterField(
            model_name='service',
            name='information_markdown',
            field=mdeditor.fields.MDTextField(verbose_name='Дополнительная информация об услуге'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=mdeditor.fields.MDTextField(verbose_name='Название услуги'),
        ),
        migrations.AlterField(
            model_name='service',
            name='text',
            field=mdeditor.fields.MDTextField(verbose_name='Текст услуги'),
        ),
        migrations.AlterField(
            model_name='servicearticle',
            name='description',
            field=mdeditor.fields.MDTextField(help_text='Первый абзац статьи', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='servicearticle',
            name='image_description',
            field=mdeditor.fields.MDTextField(max_length=400, verbose_name='Описание изображение статьи'),
        ),
        migrations.AlterField(
            model_name='servicearticle',
            name='information_markdown',
            field=mdeditor.fields.MDTextField(help_text='Поддерживает markdown.', verbose_name='Основная информация'),
        ),
    ]
