# Generated by Django 3.2.9 on 2022-01-19 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20220119_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapy',
            name='description',
        ),
    ]
