# Generated by Django 4.0.3 on 2022-04-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_previewservice_description_html_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previewservice',
            name='description_html',
            field=models.TextField(editable=False),
        ),
        migrations.AlterField(
            model_name='previewservice',
            name='name_html',
            field=models.TextField(editable=False),
        ),
    ]
