# Generated by Django 3.2.9 on 2022-01-19 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_remove_therapy_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicearticle',
            name='image_description',
        ),
    ]
