# Generated by Django 4.0.3 on 2022-04-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_previewservice_description_html_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicearticle',
            name='image_description_html',
            field=models.TextField(default='123', editable=False),
        ),
    ]
