# Generated by Django 3.2.9 on 2021-12-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_auto_20211220_0030'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Заголовок статьи')),
                ('description', models.TextField(help_text='Первый абзац статьи', verbose_name='Описание')),
                ('image', models.ImageField(help_text='Будет отображаться в статье и в ее миниатюре в списке статей.', upload_to='sys/article_images/', verbose_name='Изображение статьи')),
                ('image_description', models.TextField(max_length=400, verbose_name='Описание изображение статьи')),
                ('information_markdown', models.TextField(help_text='Поддерживает markdown.', verbose_name='Основная информация')),
                ('information_html', models.TextField(editable=False)),
            ],
            options={
                'verbose_name': 'Статья об услуги',
                'verbose_name_plural': 'Статьи об услуги',
            },
        ),
        migrations.AlterField(
            model_name='service',
            name='blog_articles',
            field=models.ManyToManyField(related_name='articles', related_query_name='articles', to='services.ServiceArticle', verbose_name='Статьи услуги'),
        ),
    ]
