# Generated by Django 3.2.9 on 2022-01-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_servicearticle_description_seo'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicearticle',
            name='title_seo',
            field=models.TextField(default='', verbose_name='Заголовок статьи для SEO'),
            preserve_default=False,
        ),
    ]
