# Generated by Django 3.2.9 on 2022-01-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_servicearticle_title_seo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicearticle',
            name='title_seo',
            field=models.TextField(blank=True, null=True, verbose_name='Заголовок статьи для SEO'),
        ),
    ]
