# Generated by Django 3.2.9 on 2022-01-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_servicearticle_title_seo'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='name_seo',
            field=models.TextField(blank=True, null=True, verbose_name='Заголовок статьи для SEO'),
        ),
    ]
