# Generated by Django 3.2.9 on 2021-12-19 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_auto_20211220_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='preview',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='services.previewservice', verbose_name='Превью для главной'),
        ),
    ]
