# Generated by Django 3.2.9 on 2022-02-07 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_service_name_seo'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicearticle',
            name='parrent_article',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parrent_article', related_query_name='parrent_article', to='services.service', verbose_name='Главная статья (Не обязательно)'),
        ),
    ]
