# Generated by Django 3.2.9 on 2022-02-07 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_servicearticle_parrent_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicearticle',
            name='parrent_article',
        ),
        migrations.AddField(
            model_name='servicearticle',
            name='parrent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.servicearticle', verbose_name='Главная статья (Не обязательно)'),
        ),
    ]
