# Generated by Django 3.2.9 on 2022-02-14 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_auto_20220208_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicearticle',
            name='parrent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.servicearticle', verbose_name='Главная статья (Не обязательно)'),
        ),
    ]
