# Generated by Django 4.0.3 on 2022-04-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_servicearticle_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicearticle',
            name='image_description',
            field=models.TextField(verbose_name='Описание изображение статьи'),
        ),
    ]
