# Generated by Django 4.0.3 on 2022-04-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_servicearticle_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='previewservice',
            name='description_html',
            field=models.TextField(default='sdf', editable=False),
        ),
        migrations.AddField(
            model_name='previewservice',
            name='name_html',
            field=models.TextField(default='sdf', editable=False),
        ),
    ]
