# Generated by Django 3.2.9 on 2021-12-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=128, verbose_name='Имя клиента')),
                ('phone_number', models.CharField(max_length=16, verbose_name='Номер телефона')),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='Дата заявки')),
            ],
            options={
                'verbose_name': 'Консультация',
                'verbose_name_plural': 'Консультации',
                'ordering': ['-date_added'],
                'get_latest_by': 'date_added',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='Дата заявки')),
                ('show_on_main', models.BooleanField(default=False, verbose_name='Показать на главной')),
            ],
            options={
                'verbose_name': 'Акции на главной',
                'verbose_name_plural': 'Акции на главной',
                'ordering': ['-date_added'],
                'get_latest_by': 'date_added',
            },
        ),
    ]
