# Generated by Django 3.2.9 on 2021-12-09 21:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=128, verbose_name='Имя клиента')),
                ('image', models.ImageField(blank=True, default='comments/default.png', upload_to='comments/', verbose_name='Аватар клиента')),
                ('text', models.TextField(verbose_name='Комментарий клиента')),
                ('estimate', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка клиента')),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='Дата добавления отзыва')),
                ('status', models.CharField(choices=[('OM', 'На модерации'), ('R', 'Отклонено'), ('A', 'Одобрено')], default='OM', max_length=2, verbose_name='Статус комментария')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-date_added'],
                'get_latest_by': 'date_added',
            },
        ),
    ]
