# Generated by Django 3.2.9 on 2022-01-24 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'get_latest_by': 'date_added', 'ordering': ['-date_added'], 'verbose_name': 'Отзывы', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.CharField(default='', max_length=30, verbose_name='Заголовок комментария клиента'),
            preserve_default=False,
        ),
    ]
