# Generated by Django 4.0.3 on 2022-05-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.CharField(default='Зубных боюсь с детства', max_length=64, verbose_name='Заголовок'),
            preserve_default=False,
        ),
    ]
