# Generated by Django 3.2.9 on 2021-12-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_alter_comment_estimate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, default='comments/default.png', null=True, upload_to='comments/', verbose_name='Аватар клиента'),
        ),
    ]
