# Generated by Django 3.2.9 on 2022-01-24 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_info', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialNetwork',
        ),
    ]
