# Generated by Django 3.2.9 on 2021-12-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='enabled_partners',
            field=models.BooleanField(default=False, help_text='Включает или отключает блок партнеров на сайте.', verbose_name='Отображать партнеров'),
        ),
    ]
