# Generated by Django 3.2.9 on 2021-12-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_info', '0002_alter_sitesettings_enabled_partners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetwork',
            name='icon',
            field=models.ImageField(upload_to='sys/social_networks_icons', verbose_name='Иконка социальной сети'),
        ),
    ]
