# Generated by Django 3.2.9 on 2021-12-09 21:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end_study',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Год окончания обучения'),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_study',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Год начала обучения'),
        ),
    ]
