# Generated by Django 3.2.9 on 2022-01-05 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='avatar_small',
            field=models.ImageField(blank=True, default='sys/employee_avatars/default.png', help_text='Фото само добавляется при добавление основого, вы можете изменить его', upload_to='sys/employee_avatars/', verbose_name='Маленькая Аватар сотрудника'),
        ),
    ]
