# Generated by Django 3.2.9 on 2022-01-19 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_avatar_small'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='avatar_small',
            field=models.ImageField(blank=True, default='sys/employee_avatars/default.png', help_text='Автоматически добавляется при добавление основого, вы можете изменить его', upload_to='sys/employee_avatars/', verbose_name='Маленькая Аватар сотрудника'),
        ),
    ]
