# Generated by Django 3.2.9 on 2021-12-09 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20211210_0445'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skilldevelop',
            options={'verbose_name': 'Повышение квалификации', 'verbose_name_plural': 'Повышения квалификаций'},
        ),
    ]
