# Generated by Django 3.2.9 on 2022-02-03 16:52

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_avatar_small'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('avatar', '430x360', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
