# Generated by Django 3.2.9 on 2021-12-19 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_skilldevelop_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='education', related_query_name='education', to='employees.employee'),
        ),
    ]
