# Generated by Django 3.2.9 on 2022-02-07 21:59

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_cropping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='avatar_small',
            field=models.ImageField(blank=True, default='sys/employee_avatars/default.png', editable=False, help_text='Автоматически добавляется при добавление основого, вы можете изменить его', upload_to='sys/employee_avatars/', verbose_name='Маленькая Аватар сотрудника'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('avatar', '270x360', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Маленькая Аватар сотрудника'),
        ),
    ]
